#!/bin/bash
# Copyright (c) Paul R. Tagliamonte <tag@pault.ag>, 2013 under the terms
# and conditions of the MIT/Expat license.

DIST=unstable

if [ "x$1" = "x" ]; then
    echo "Error: - usage:"
    echo "  $0 unstable"
    exit 1
fi

DIST=$1

WORKDIR=$(mktemp -d)
mkdir ${WORKDIR}/tmp

CONTAINER=$(docker run \
    -d \
    -privileged \
    -u root \
    -v ${WORKDIR}:/mnt/workdir \
    paultag/sbuild-createchroot \
    sbuild-createchroot \
        --make-sbuild-tarball=/tmp/${DIST}.tar.gz \
        ${DIST} \
        /mnt/workdir/tmp/ \
        http://http.debian.net/debian)

docker attach ${CONTAINER}
docker wait ${CONTAINER}
docker cp ${CONTAINER}:/tmp/${DIST}.tar.gz .
docker rm ${CONTAINER}
