# sbuild-createchroot
#
# VERSION               0.0.1

FROM tianon/debian
MAINTAINER Paul R. Tagliamonte "paultag@debian.org"

RUN cat /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y sbuild schroot
